import { useState } from 'react';
import PrivateTaskCard from '../../components/PrivateTaskCard';
import { vimeoReviewEmbed } from '../../utils/vimeoReview.mjs';
import { Badge, ConfirmAction, date, Notice, Pager, query, Search, Table, useApi, useResource } from './common';

export default function Approvals({ kind, openPerson, owner }) {
  const [page, setPage] = useState(1), [q, setQ] = useState(''), [status, setStatus] = useState('pending'), [selected, setSelected] = useState(null), [decision, setDecision] = useState(null), [bulk, setBulk] = useState(null);
  const api = useApi(), resource = useResource(`/operations/approvals/${kind}?${query({ page, q, status })}`), [price, setPrice] = useState('');
  const counts = useResource('/operations/overview'), countKey = { scholars: 'scholarApplications', courses: 'courseApplications', videos: 'videoReviews' }[kind];
  const closeReview = () => setSelected(null);
  const resetResults = () => { closeReview(); resource.reload(); counts.reload(); };
  const review = row => {
    const embed = kind === 'videos' ? vimeoReviewEmbed(row.video_url) : null;
    return <section className="ops-inset ops-inline-review" aria-label={`Review ${row.title || row.id}`}><div className="ops-section-heading"><h3>{row.title || `${row.fname} ${row.lname}`}</h3><button onClick={closeReview}>Close review</button></div><p>{row.university || row.course} · {row.degree}</p>{row.year && <p>Study year: {row.year}</p>}<p className="ops-prose">{row.expertise || row.description || 'No description provided.'}</p>{row.task_card_url && <PrivateTaskCard key={row.user_id} userId={row.user_id} />}{kind === 'videos' && <><p>{row.course} · Intended lesson order: <strong>{row.sequence_index}</strong></p>{embed ? <iframe className="ops-video-player" src={embed} title={`Review video: ${row.title}`} allow="fullscreen; picture-in-picture" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" /> : <p>Video preview URL unavailable. Do not approve before reviewing the content.</p>}</>}{owner && kind === 'videos' && !row.approved && <label>Video price (EUR; first lesson remains free)<input aria-label="Video price" type="number" min="0" step="0.01" value={price} onChange={e => setPrice(e.target.value)} /></label>}{!row.approved && <div className="ops-actions"><button className="ops-primary" onClick={() => setDecision('approve')}>Approve</button><button onClick={() => setDecision('reject')}>Reject</button></div>}</section>;
  };
  return <><div className="ops-section-heading"><h2>{{ scholars: 'Scholar applications', courses: 'Course applications', videos: 'Video reviews' }[kind]}</h2><Badge>{counts.data ? `${counts.data[countKey]} pending` : 'Count unavailable'}</Badge></div><div className="ops-filters"><Search onSearch={value => { setQ(value); setPage(1); closeReview(); }} /><select aria-label="Approval status" value={status} onChange={e => { setStatus(e.target.value); setPage(1); closeReview(); }}><option value="pending">Pending</option><option value="approved">Approved</option><option value="all">All</option></select></div><Notice {...resource}><Table rows={resource.data?.rows} expandedRow={kind === 'videos' ? row => selected?.id === row.id ? review(row) : null : undefined} columns={[
    ['Applicant', row => <button className="ops-link" onClick={() => openPerson(row.user_id)}>{row.fname} {row.lname}<small>{row.email}</small></button>],
    ['Application', row => <>{row.title || row.university}<small>{row.course || row.degree}</small>{row.sequence_index && <Badge>Lesson {row.sequence_index}</Badge>}{kind === 'videos' && <small>{row.course_video_count} videos · {row.pending_video_count} pending in this offering</small>}</>],
    ['Status', row => <Badge>{row.approved ? 'Approved' : 'Pending'}</Badge>], ['Submitted', row => date(row.created_at)],
    ['Review', row => <div className="ops-actions"><button aria-expanded={selected?.id === row.id} onClick={() => { if (kind === 'videos' && selected?.id === row.id) closeReview(); else { setSelected(row); setPrice(String(row.price ?? 0)); } }}>{kind === 'videos' && selected?.id === row.id ? 'Close review' : 'Open review'}</button>{kind === 'videos' && row.offering_id && Number(row.pending_video_count) > 0 && <button onClick={() => setBulk(row)}>Approve all {row.pending_video_count} pending</button>}</div>]
  ]} /><Pager data={resource.data} setPage={value => { setPage(value); closeReview(); }} /></Notice>
    {selected && kind !== 'videos' && review(selected)}
    {decision && <ConfirmAction title={`${decision === 'approve' ? 'Approve' : 'Reject'} this submission`} phrase={`${decision.toUpperCase()} ${selected.id}`} explanation={`Review for ${selected.fname} ${selected.lname}. ${decision === 'reject' ? 'The pending submission will be removed only if it has no protected references. This does not delete the user or financial history.' : 'This changes the approval state. Video approval makes that lesson available through the existing course flow.'}`} onClose={() => setDecision(null)} onConfirm={async () => { await api(`/operations/approvals/${kind}/${selected.id}`, 'POST', { decision, ...(owner && kind === 'videos' && decision === 'approve' ? { price } : {}) }); resetResults(); }} />}
    {bulk && <ConfirmAction title={`Approve ${bulk.pending_video_count} pending videos`} phrase={`APPROVE ${bulk.pending_video_count} VIDEOS #${bulk.offering_id}`} explanation={`Course: ${bulk.course}. Scholar: ${bulk.fname} ${bulk.lname}. Approve all ${bulk.pending_video_count} currently pending videos in this exact offering only after reviewing their content. Prices, lesson order and Vimeo references remain unchanged.`} onClose={() => setBulk(null)} onConfirm={async confirmation => { await api(`/operations/approvals/videos/offering/${bulk.offering_id}/approve-pending`, 'POST', { confirmation, count: Number(bulk.pending_video_count), subjectId: bulk.subject_id, scholarId: bulk.user_id, course: bulk.course }); resetResults(); }} />}
  </>;
}
