import { useState } from 'react';
import { useAuth } from '../../context/temp';
import { Badge, date, Form, Notice, Pager, query, Search, Table, useApi, useResource } from './common';

export default function Cases({ kind = 'support', userId, openPerson, initialLinks = {} }) {
  const { user } = useAuth(), api = useApi();
  const staff = user?.roles?.some(r => ['Admin', 'SuperAdmin'].includes(r)), owner = user?.roles?.includes('SuperAdmin'), escalation = kind === 'escalations';
  const [page, setPage] = useState(1), [q, setQ] = useState(''), [status, setStatus] = useState(''), [category, setCategory] = useState(''), [selected, setSelected] = useState(null), [creating, setCreating] = useState(false);
  const [newCategory, setNewCategory] = useState('');
  const options = useResource('/operations/case-options');
  const categories = options.data?.[escalation ? 'escalationCategories' : 'categories'] || [];
  const resource = useResource(`/operations/${kind}?${query({ page, q, status, category, userId })}`);
  const statuses = escalation ? ['OPEN', 'IN_REVIEW', 'RESOLVED'] : ['OPEN', 'IN_PROGRESS', 'RESOLVED'];
  if (selected) return <CaseDetail key={`${kind}-${selected}`} {...{ kind, selected, staff, owner, openPerson, statuses }} close={() => { setSelected(null); resource.reload(); }} />;
  return <><div className="ops-section-heading"><div><h2>{escalation ? 'Escalations' : 'Support cases'}</h2><p>{escalation ? 'Request owner review. Creating a case does not execute a financial action.' : staff ? 'Help learners and Scholars across all universities.' : 'Follow your requests and replies from the UniClips team.'}</p></div>{!userId && <button className="ops-primary" disabled={resource.loading || !!resource.error || resource.data?.available === false} onClick={() => setCreating(!creating)}>{creating ? 'Close form' : escalation ? 'New escalation' : 'New support request'}</button>}</div>
    {creating && resource.data?.available !== false && <section className="ops-inset"><Form label={escalation ? 'Create escalation' : 'Send request'} submit={body => api(`/operations/${kind}`, 'POST', body)} onSaved={() => { setCreating(false); resource.reload(); }}><label>Category<select aria-label="Request category" name="category" required value={newCategory} onChange={e => setNewCategory(e.target.value)}><option value="">Choose category</option>{categories.map(c => <option key={c}>{c}</option>)}</select></label><label>Subject<input name={escalation ? 'title' : 'subject'} maxLength={180} required /></label><label>Description<textarea name="description" maxLength={4000} rows={5} required /></label>{escalation && <><label>Priority<select name="priority"><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select></label><div className="ops-field-grid">{[['related_user_id', 'Related user ID'], ['support_case_id', 'Support case ID'], ['order_id', 'Payment Phase 2A order ID'], ['subject_id', 'Course subject ID']].map(([name, label]) => <label key={name}>{label} (optional)<input name={name} defaultValue={initialLinks[name] || ''} /></label>)}</div></>}</Form></section>}
    <div className="ops-filters"><Search placeholder="Search subject, reference or email" onSearch={v => { setQ(v); setPage(1); }} /><select aria-label="Status" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">All statuses</option>{statuses.map(s => <option key={s}>{s}</option>)}</select><select aria-label="Category" value={category} onChange={e => { setCategory(e.target.value); setPage(1); }}><option value="">All categories</option>{categories.map(c => <option key={c}>{c}</option>)}</select></div>
    <Notice {...resource}><Table rows={resource.data?.rows} columns={[
      ['Case', r => <button className="ops-link" onClick={() => setSelected(r.id)}>{r.reference} · {r.subject || r.title}</button>], ['Category', r => r.category], ['Status', r => <><Badge>{r.status}</Badge>{r.priority && <Badge>{r.priority}</Badge>}</>], ['Person', r => r.person_name], ['Created', r => date(r.created_at)]
    ]} /><Pager data={resource.data} setPage={setPage} /></Notice></>;
}
function CaseDetail({ kind, selected, staff, owner, openPerson, statuses, close }) {
  const api = useApi(), escalation = kind === 'escalations', path = `/operations/${kind}/${selected}`;
  const resource = useResource(path), [older, setOlder] = useState([]), [more, setMore] = useState(null), [error, setError] = useState('');
  const row = resource.data, canManage = escalation ? owner : staff;
  const [escalate, setEscalate] = useState(false);
  if (escalate) return <><button onClick={() => setEscalate(false)}>Back to support case</button><Cases kind="escalations" initialLinks={{ support_case_id: selected, related_user_id: row.user_id }} /></>;
  return <><button onClick={close}>← Back to cases</button><Notice {...resource}>{row && <><div className="ops-section-heading"><div><h2>{row.reference} · {row.subject || row.title}</h2><Badge>{row.status}</Badge>{row.priority && <Badge>{row.priority}</Badge>}</div><span>{date(row.created_at)}</span></div><p className="ops-prose">{row.description}</p><p>Assigned to: {row.assigned_name || 'Unassigned'}</p>{staff && <div className="ops-actions">{openPerson && <button onClick={() => openPerson(row.user_id || row.created_by)}>View person</button>}{!escalation && <button onClick={() => setEscalate(true)}>Escalate to SuperAdmin</button>}</div>}
    {escalation && <p>Related references: {[['User', row.related_user_id], ['Support case', row.support_case_id], ['Order', row.order_id], ['Subject', row.subject_id]].filter(([, v]) => v).map(([k, v]) => `${k} ${v}`).join(' · ') || 'None'}</p>}
    {canManage && <details className="ops-inset"><summary>Assignment and status</summary><Form key={row.status} submit={body => api(path, 'PATCH', body)} onSaved={resource.reload}><label>Status<select name="status" defaultValue={row.status}>{statuses.filter((s, i) => i >= statuses.indexOf(row.status) && i <= statuses.indexOf(row.status) + 1).map(s => <option key={s}>{s}</option>)}</select></label><label>Assign to authorized {escalation ? 'SuperAdmin' : 'Admin'} user ID<input type="number" min="1" name="assignedTo" defaultValue={row.handled_by || row.assigned_to || ''} /></label>{escalation && <label>Resolution (required when resolving)<textarea name="resolution" maxLength={4000} defaultValue={row.resolution || ''} /></label>}</Form></details>}
    <h3>History</h3>{error && <p role="alert">{error}</p>}{(more ?? row.hasMore) && <button onClick={async () => { try { const result = await api(`${path}?before=${older[0]?.id || row.messages[0]?.id}`); setOlder(v => [...result.messages, ...v]); setMore(result.hasMore); } catch (e) { setError(e.message); } }}>Load older messages</button>}
    {[...older, ...row.messages].map(m => <article key={m.id} className={`ops-message ${m.internal ? 'ops-note' : ''}`}><strong>{m.author || 'Former account'}</strong> · {date(m.created_at)} {m.internal ? <Badge>Internal note</Badge> : null}<p className="ops-prose">{m.body}</p></article>)}{!row.messages.length && <p className="ops-empty">No replies yet.</p>}
    <Form label="Add message" submit={body => api(`${path}/messages`, 'POST', { ...body, internal: body.internal === 'on' })} onSaved={resource.reload}><label>Message<textarea name="body" rows={4} maxLength={4000} required /></label>{staff && !escalation && <label className="ops-check"><input type="checkbox" name="internal" /> Internal note — visible to administrators only</label>}</Form>
    </>}</Notice></>;
}
