import { useState } from 'react';
import { Badge, ConfirmAction, date, Form, formatMoney, Notice, Pager, query, Search, Table, useApi, useResource } from './common';

export function Catalogue({ pricing = false }) {
  const api = useApi(), [page, setPage] = useState(1), [q, setQ] = useState(''), [university, setUniversity] = useState(''), [programme, setProgramme] = useState(''), [selected, setSelected] = useState(null), [price, setPrice] = useState(''), [confirm, setConfirm] = useState(false);
  const universities = useResource('/locations/universities?available=1'), programmes = useResource(university ? `/locations/programs/by-university/${university}` : '/locations/programs/all'), resource = useResource(`/operations/catalogue?${query({ page, q, university, programme })}`);
  return <><h2>{pricing ? 'Course pricing' : 'Academic catalogue'}</h2><p>{pricing ? 'Only existing Finnish EUR catalogue prices can be changed. Nigerian checkout and NGN pricing remain disabled.' : 'Read-only navigation preserves programme mappings, course IDs and derived General University Course classification.'}</p><div className="ops-filters"><Search placeholder="Search course name" onSearch={v => { setQ(v); setPage(1); }} /><select aria-label="University" value={university} onChange={e => { setUniversity(e.target.value); setProgramme(''); setPage(1); }}><option value="">All universities</option>{universities.data?.map(u => <option key={u.id} value={u.id}>{u.country_name} · {u.name}</option>)}</select><select aria-label="Programme" value={programme} onChange={e => { setProgramme(e.target.value); setPage(1); }}><option value="">All programmes</option>{programmes.data?.map(p => <option key={p.program} value={p.program}>{p.program}</option>)}</select></div>{universities.error && <Notice {...universities} />}{programmes.error && <Notice {...programmes} />}<Notice {...resource}><Table rows={resource.data?.rows} columns={[
    ['Course', r => <>{r.name}<small>Subject #{r.id}</small></>], ['Academic context', r => <>{r.university}<small>{r.degree_programmes}</small></>], ['Classification', r => r.is_general_university_course ? <>{r.course_category_label}<details className="ops-programmes"><summary>{r.distinct_programme_count} programmes</summary><ul>{r.applicable_programmes?.map(p => <li key={p}>{p}</li>)}</ul></details></> : 'Programme course'], ...(pricing ? [['Price', r => r.country_code === 'FI' ? <>{formatMoney(r.bundle_price, 'EUR')} <button onClick={() => { setSelected(r); setPrice(r.bundle_price); }}>Change price</button></> : 'Nigeria pricing not enabled']] : [])
  ]} /><Pager data={resource.data} setPage={setPage} /></Notice>{selected && <section className="ops-inset"><h3>{selected.name}</h3><label>New price (EUR)<input inputMode="decimal" value={price} onChange={e => setPrice(e.target.value)} /></label><div className="ops-actions"><button onClick={() => setSelected(null)}>Cancel</button><button onClick={() => setConfirm(true)}>Review price change</button></div></section>}{confirm && <ConfirmAction title="Change catalogue price" explanation={`${selected.name}: ${formatMoney(selected.bundle_price)} → ${price} EUR. Existing purchases are unchanged.`} phrase={`PRICE ${selected.id}`} onClose={() => setConfirm(false)} onConfirm={async confirmation => { await api(`/operations/catalogue/${selected.id}/price`, 'PUT', { price, confirmation }); setSelected(null); resource.reload(); }} />}</>;
}
export function Finance({ view = 'allocations' }) {
  const [page, setPage] = useState(1), [release, setRelease] = useState(null), api = useApi(), resource = useResource(`/operations/finance?${query({ page, view })}`);
  return <><h2>{{ allocations: 'Scholar allocations & transfers', legacy: 'Historical transfer records', review: 'Financial review' }[view]}</h2><p>{view === 'legacy' ? 'Historical Transfer Records were created under the legacy Stripe flow.' : 'Scholar Allocations & Transfers record the authoritative lifecycle for new Phase 2A orders after that schema is migrated.'}</p><p>Payment, entitlement, Scholar allocation, transfer to a connected account and bank payout are separate stages. Bank receipt is not established by a transfer record.</p><Notice {...resource}>{resource.data?.available === false ? <p className="ops-empty">{resource.data.message}</p> : <><Table rows={resource.data?.rows} columns={view === 'legacy' ? [
    ['Scholar', r => r.scholar], ['Recorded amount', r => formatMoney(r.amount, r.currency)], ['Recorded status', r => <Badge>{r.status}</Badge>], ['Transfer reference', r => r.stripe_transfer_id || 'Not recorded'], ['Date', r => date(r.created_at)]
  ] : view === 'review' ? [
    ['Order', r => r.id], ['Amount', r => formatMoney(r.amount_minor / 100, r.currency)], ['Payment', r => <Badge>{r.state}</Badge>], ['Transfer', r => r.transfer_state || 'No allocation'], ['Refund / dispute', r => `${r.refund_state} / ${r.dispute_state}`], ['Review detail', r => r.error_code || 'Review provider evidence before intervention']
  ] : [
    ['Allocation', r => <>{r.scholar}<small>{r.course}</small><small className="ops-reference">{r.id}</small></>], ['Scholar earned', r => <>{formatMoney(r.scholar_minor / 100, r.currency)}<small>Sale {r.sale_ordinal} · {r.scholar_rate}%</small></>], ['Platform allocation', r => formatMoney(r.platform_minor / 100, r.currency)], ['Transfer', r => <><Badge>{r.transfer_state}</Badge><small>{r.transfer_id || 'No completed reference'}</small></>], ['Action', r => r.transfer_state === 'pending' && r.refund_state === 'none' && r.dispute_state === 'none' ? <button onClick={() => setRelease(r)}>Review release</button> : 'Reconcile if action is required']
  ]} /><Pager data={resource.data} setPage={setPage} /></>}</Notice>{release && <ConfirmAction title="Release recorded Scholar allocation" phrase={`TRANSFER ${release.id}`} explanation={`This invokes the existing Stripe transfer service for ${formatMoney(release.scholar_minor / 100, release.currency)} to ${release.scholar}. It is a real money movement when deployed with live credentials. It is not a bank payout.`} onClose={() => setRelease(null)} onConfirm={async confirmation => { await api('/stripe-connect/payout', 'POST', { orderId: release.id, confirmation }); resource.reload(); }} />}</>;
}
export function Profile() {
  const api = useApi(), resource = useResource('/admin/profile');
  return <><h2>My profile</h2><Notice {...resource}>{resource.data && <Form submit={body => api('/admin/profile', 'PUT', body)}><p>{resource.data.email}</p><div className="ops-field-grid">{[['firstname', 'First name'], ['lastname', 'Last name'], ['display_name', 'Display name'], ['phone', 'Phone'], ['department', 'Department']].map(([key, label]) => <label key={key}>{label}<input name={key} defaultValue={resource.data[key] || ''} required={['firstname', 'lastname'].includes(key)} maxLength={100} /></label>)}</div><label>Bio<textarea name="bio" defaultValue={resource.data.bio || ''} maxLength={2000} /></label></Form>}</Notice></>;
}
export function AdminCreate() {
  const api = useApi();
  return <details className="ops-inset"><summary>Create a General Admin</summary><p>General Admin has operational authority across all universities, including users without a university. Use Person 360 for a separately confirmed SuperAdmin promotion.</p><Form label="Create Admin" submit={body => api('/operations/admins', 'POST', { ...body, role: 'Admin' })}><div className="ops-field-grid"><label>First name<input name="firstname" required maxLength={100} /></label><label>Last name<input name="lastname" required maxLength={100} /></label><label>Email<input name="email" type="email" required /></label><label>Initial password<input name="password" type="password" minLength={12} maxLength={200} required autoComplete="new-password" /></label></div><label>Type CREATE ADMIN followed by the exact lowercase email<input name="confirmation" required autoComplete="off" /></label></Form></details>;
}
export function Audit() {
  const [page, setPage] = useState(1), [q, setQ] = useState(''), resource = useResource(`/operations/activity?${query({ page, q })}`);
  return <><h2>Activity history</h2><Search placeholder="Search action or target type" onSearch={v => { setQ(v); setPage(1); }} /><Notice {...resource}><Table rows={resource.data?.rows} columns={[
    ['Actor', r => r.actor || `Account #${r.user_id}`], ['Action', r => r.action], ['Target', r => `${r.target_type || ''} ${r.target_id || ''}`], ['Details', r => typeof r.details === 'string' ? r.details : JSON.stringify(r.details)], ['Time', r => new Date(r.created_at).toLocaleString()]
  ]} /><Pager data={resource.data} setPage={setPage} /></Notice></>;
}
export function Security() {
  const [page, setPage] = useState(1), api = useApi(), resource = useResource(`/operations/security?page=${page}`), [selected, setSelected] = useState(null);
  return <><h2>Security oversight</h2><p>Recorded alerts and their resolution state. This is not a certification that the platform is secure. Privileged activity is available in the Audit Log.</p><details className="ops-inset"><summary>Record security alert</summary><Form submit={body => api('/operations/security', 'POST', body)} onSaved={resource.reload}><label>Title<input name="title" maxLength={180} required /></label><label>Description<textarea name="description" required maxLength={4000} /></label><label>Severity<select name="severity">{['low', 'medium', 'high', 'critical'].map(s => <option key={s}>{s}</option>)}</select></label></Form></details><Notice {...resource}><Table rows={resource.data?.rows} empty="No security alerts recorded." columns={[
    ['Alert', r => <>{r.title}<small>{r.description}</small></>], ['Severity', r => <Badge>{r.severity}</Badge>], ['Status', r => <Badge>{r.status}</Badge>], ['Created', r => date(r.created_at)], ['Action', r => <button onClick={() => setSelected(r)}>Update status</button>]
  ]} /><Pager data={resource.data} setPage={setPage} /></Notice>{selected && <section className="ops-inset"><h3>{selected.title}</h3><Form submit={body => api(`/operations/security/${selected.id}/status`, 'PUT', body)} onSaved={() => { setSelected(null); resource.reload(); }}><label>Status<select name="status" defaultValue={selected.status}>{['pending', 'in-progress', 'resolved'].map(s => <option key={s}>{s}</option>)}</select></label></Form></section>}</>;
}
