import { useState } from 'react';
import { Badge, ConfirmAction, date, formatMoney, Form, Notice, Pager, query, Search, Subnav, Table, useApi, useResource } from './common';
import Cases from './Cases';

export default function People({ owner, personId, openPerson, closePerson, adminOnly = false }) {
  const [q, setQ] = useState(''), [page, setPage] = useState(1), [role, setRole] = useState(adminOnly ? 'Admin' : ''), [university, setUniversity] = useState(''), [programme, setProgramme] = useState('');
  const universities = useResource('/operations/universities');
  const resource = useResource(`/operations/people?${query({ q, page, role, university, programme })}`);
  if (personId) return <Person key={personId} {...{ personId, owner, openPerson }} close={closePerson} />;
  return <><h2>{adminOnly ? 'Admins & permissions' : 'People'}</h2><p>{adminOnly ? 'Admins have General Admin access across all universities. Restricted scopes and account suspension are not enabled.' : 'Find a learner or Scholar, including people without a university.'}</p><div className="ops-filters"><Search onSearch={v => { setQ(v); setPage(1); }} /><select aria-label="Role" value={role} onChange={e => { setRole(e.target.value); setPage(1); }}><option value="">All roles</option>{['Learner', 'Scholar', 'Admin', 'SuperAdmin'].map(r => <option key={r}>{r}</option>)}</select><select aria-label="University" value={university} onChange={e => { setUniversity(e.target.value); setPage(1); }}><option value="">All universities</option><option value="unassigned">No university</option>{universities.data?.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select><input aria-label="Exact programme" placeholder="Exact programme (optional)" value={programme} onChange={e => { setProgramme(e.target.value); setPage(1); }} /></div><Notice {...resource}><Table rows={resource.data?.rows} columns={[
    ['Person', r => <><button className="ops-link" onClick={() => openPerson(r.id)}>{r.fname} {r.lname}</button><small>{r.email}</small></>], ['Role', r => r.roles || 'No role'], ['Study preferences', r => <>{r.university || 'No university selected'}<small>{r.degree_programme || 'No programme selected'}</small></>], ['Joined', r => date(r.created_at)], ['Action', r => <button onClick={() => openPerson(r.id)}>View person</button>]
  ]} /><Pager data={resource.data} setPage={setPage} /></Notice></>;
}
function Person({ personId, owner, close, openPerson }) {
  const person = useResource(`/operations/people/${personId}`), [section, setSection] = useState('overview'), [action, setAction] = useState(null), api = useApi();
  const row = person.data;
  return <><button onClick={close}>← Back to previous workspace</button><Notice {...person}>{row && <><div className="ops-section-heading"><div><h2>{row.fname} {row.lname}</h2><p>{row.email}</p><Badge>{row.roles}</Badge></div><span>Person #{row.id}</span></div><Subnav items={[['overview', 'Overview'], ['learning', 'Learning'], ['purchases', 'Purchases'], ['requests', 'Requests'], ...(row.scholar ? [['scholar', 'Scholar']] : [])]} value={section} onChange={setSection} />
    {section === 'overview' ? <><dl className="ops-facts"><dt>Account</dt><dd>{row.accountStatus}</dd><dt>Joined</dt><dd>{date(row.created_at)}</dd><dt>Learner university</dt><dd>{row.university || 'Not selected'}</dd><dt>Learner programme</dt><dd>{row.degree_programme || 'Not selected'}</dd><dt>Scholar context</dt><dd>{row.scholar ? `${row.scholar.approved ? 'Approved' : 'Pending'} · ${row.scholar.university} · ${row.scholar.degree}` : 'No Scholar application'}</dd></dl>{owner && <details className="ops-inset"><summary>Privileged account actions</summary><details className="ops-inset"><summary>Update name or email</summary><Form submit={body => api(`/operations/people/${row.id}`, 'PUT', body)} onSaved={person.reload}><label>First name<input name="fname" defaultValue={row.fname} required maxLength={100} /></label><label>Last name<input name="lname" defaultValue={row.lname} required maxLength={100} /></label><label>Email<input type="email" name="email" defaultValue={row.email} required /></label><label>Type UPDATE {row.email}<input name="confirmation" required /></label></Form></details><p>Role changes replace the account’s current role. Admin grants operational access across all universities; SuperAdmin grants platform, financial and security authority. Your own privileges cannot be changed here.</p><div className="ops-actions">{['Learner', 'Scholar', 'Admin', 'SuperAdmin'].map(role => <button key={role} onClick={() => setAction({ type: 'role', role })}>Set {role}</button>)}<button onClick={() => setAction({ type: 'delete' })}>Delete unreferenced account</button></div><p>Accounts with historical financial, content, support or audit references cannot be permanently deleted because those records must be preserved.</p><p>Account suspension is not yet implemented.</p></details>}</> : section === 'requests' ? <Cases userId={personId} {...{ openPerson }} /> : <PersonRecords key={section} {...{ personId, section }} />}
    {action && <ConfirmAction title={`${action.type === 'delete' ? 'Delete account' : `Grant ${action.role}`} · ${row.fname} ${row.lname}`} explanation={`Target: ${row.email}. ${action.type === 'delete' ? 'Permanent deletion is permitted only for an unreferenced, non-privileged account.' : action.role === 'SuperAdmin' ? 'This grants full owner authority, including role administration, pricing and financial release.' : 'This replaces existing roles. Approved academic context is preserved.'}`} phrase={action.type === 'delete' ? `DELETE ${row.email}` : `${action.role === 'SuperAdmin' ? 'GRANT SUPERADMIN' : action.role === 'Admin' ? 'GRANT ADMIN' : 'CHANGE ROLE'} ${row.email}`} onClose={() => setAction(null)} onConfirm={async confirmation => { await api(`/operations/people/${row.id}${action.type === 'role' ? '/role' : ''}`, action.type === 'delete' ? 'DELETE' : 'PUT', { confirmation, role: action.role }); if (action.type === 'delete') close(); else person.reload(); }} />}
    </>}</Notice></>;
}
function PersonRecords({ personId, section }) {
  const [page, setPage] = useState(1), resource = useResource(`/operations/people/${personId}?${query({ section, page })}`), data = resource.data;
  return <Notice {...resource}>{section === 'learning' ? <Table rows={data?.rows} columns={[
    ['Course', r => r.course || 'Historical course'], ['Access', r => <Badge>{r.active ? 'Active' : 'Expired / inactive'}</Badge>], ['Expires', r => date(r.access_expires_at)], ['Progress', r => r.lessons ? `${r.watched} / ${r.lessons} approved lessons completed` : 'No active approved lessons'], ['Purchased', r => date(r.created_at)]
  ]} /> : section === 'purchases' ? <><PaymentAvailability data={data} /><TransactionTable rows={data?.rows} /></> : <><p>{data?.application ? `${data.application.approved ? 'Approved' : 'Pending'} · ${data.application.university} · ${data.application.degree}` : 'No application'}</p><p>{data?.content?.map(c => `${c.count} ${c.approved ? 'published' : 'pending'} videos`).join(' · ') || 'No uploaded videos'}</p><Table rows={data?.courses?.rows} columns={[
    ['Course application', r => r.course], ['Programme', r => r.degree], ['Expertise', r => r.expertise], ['Status', r => <Badge>{r.approved ? 'Approved' : 'Pending'}</Badge>]
  ]} /></>}<Pager data={section === 'scholar' ? data?.courses : data} setPage={setPage} /></Notice>;
}
export function TransactionTable({ rows }) {
  return <Table rows={rows} columns={[
    ['Reference', r => <><span className="ops-reference">{r.reference}</span><small>{r.provider} · {date(r.created_at)}</small></>], ['Learner / course', r => <>{r.learner}<small>{r.reference.startsWith('video-') ? 'Historical video record' : r.course || 'Historical course'} · Scholar: {r.scholar || 'Not recorded'}</small></>], ['Amount', r => formatMoney(r.amount, r.currency)], ['Payment', r => <><Badge>{r.status}</Badge>{r.reference.startsWith('video-') && <small>Retained history; excluded from course totals and Scholar earnings/payable balance.</small>}</>], ['Entitlement', r => r.active == null ? 'Not recorded / not fulfilled' : <>{r.active ? 'Active' : 'Expired / inactive'}<small>Expires: {date(r.access_expires_at)}</small></>]
  ]} />;
}
export function Transactions() {
  const [page, setPage] = useState(1), [q, setQ] = useState(''), [currency, setCurrency] = useState('');
  const resource = useResource(`/operations/transactions?${query({ page, q, currency })}`);
  return <><h2>Transactions</h2><p>Observation only. A recorded legacy purchase is not proof of a reconciled provider payment. Escalate financial intervention through Support → Escalations.</p><div className="ops-filters"><Search placeholder="Search reference, email or course" onSearch={v => { setQ(v); setPage(1); }} /><input aria-label="Currency" placeholder="Currency, e.g. EUR" maxLength={3} value={currency} onChange={e => { setCurrency(e.target.value.toUpperCase()); setPage(1); }} /></div><Notice {...resource}><PaymentAvailability data={resource.data} /><TransactionTable rows={resource.data?.rows} /><Pager data={resource.data} setPage={setPage} /></Notice></>;
}

function PaymentAvailability({ data }) { return data?.phase2aAvailable === false ? <p role="status" className="ops-empty">{data.message}</p> : null; }
